two additional rules
Logius-standaarden/API-Design-Rules pull request #136
Opened 2023-06-08 15:37 UTC by mrtn78

Added two additional rules regarding:
- backward compatibility
- sunsetting APIs

2023-06-08 15:38 UTC, mrtn78 commented
relates to: https://github.com/Geonovum/KP-APIs/issues/468

2023-09-07 12:22 UTC, joostfarla requested changes

2023-09-07 12:22 UTC, joostfarla commented on DesignRules.md
> +         Backward-compatible changes that do not affect any of the clients include the addition of new operations and schemas. Also, depending on the client's expectations, the addition of optional f
Deze beschrijving lijkt mij eerder onderdeel van het statement. Rationale beschrijft alleen het "waarom".

2023-09-07 12:22 UTC, joostfarla commented on DesignRules.md
> +  <p class="rulelab"><b>/core/backward-compatibility</b>: The API designer should strive for backward-compatible changes</p>
Het nadeel van deze design rule vind ik dat het niet SMART geformuleerd is. We zouden het misschien ook als uitbreiding op kunnen nemen in de bestaande SemVer rule als een soort best practice.

2023-09-07 12:22 UTC, joostfarla commented on DesignRules.md
> +         <p>This rule follows the [[eDelivery API4IPS]] specification.</p>
Aangezien deze rule van algemene aard is, lijkt deze verwijzing onnodig (anders zou je dit bij iedere rule moeten doen die overeenkomt met API4IPS).

2023-09-07 12:22 UTC, joostfarla commented on DesignRules.md
> +         For sunsetting the API, the OpenAPI Document of the API must contain in the <code>info.x- edelivery.lifecycle</code> property the following declared attributes:
Met het aanpassen van `x-edelivery` naar `x-nlgov` ben je niet meer API4IPS compliant.

2023-09-07 12:22 UTC, joostfarla commented on DesignRules.md
> +  <p class="rulelab"><b>/core/sunset</b>: Sunsetting of operations is done with the use of semantic versioning</p>
Aangezien deze rule eDelivery-specifieke zaken bevat zou ik deze niet in de core module verwachten, maar eerder in een (toekomstige) eDelivery module. Gezien de premature status van het eDelivery profiel zou ik deze even parkeren voor de toekomst.

2023-09-07 12:22 UTC, joostfarla commented on Summary.md
> +Additional eDelivery compliant rules:
Het lijkt me niet wenselijk om deze onderverdeling zo expliciet te maken. Ik zou daarom eerdere pleiten voor een aparte eDelivery module. Design rules die van algemene aard zijn (zoals `/core/backward-compatibility`) kunnen gewoon in het standaard lijstje.

2023-09-20 15:02 UTC, mrtn78 commented on DesignRules.md
> +         For sunsetting the API, the OpenAPI Document of the API must contain in the <code>info.x- edelivery.lifecycle</code> property the following declared attributes:
dit inderdaad een fundamenteel punt. willen we compliant zijn aan API4IPS dan moeten we in alle OAS files een x-edelivery property opnemen. Ik parkeer deze RFC voor een later moment om een meer fundamentele discussie te voeren in de werkgroep en stuurgroep over edelivery.

2023-09-20 15:04 UTC, mrtn78 commented on DesignRules.md
> +  <p class="rulelab"><b>/core/sunset</b>: Sunsetting of operations is done with the use of semantic versioning</p>
Meen eens. we parkeren deze

2023-09-20 15:05 UTC, mrtn78 commented
Besloten om deze change nu niet door te voeren en eerst breed de discussie te starten over de samenhang van de NLGov API Strategie en edelivery API4IPS

2024-10-23 09:42 UTC, TheBonheurs commented on DesignRules.md
> +  <p class="rulelab"><b>/core/backward-compatibility</b>: The API designer should strive for backward-compatible changes</p>
Ik ben late to the party, maar eens over het feit dat dit niet super is uitgedrukt. 

Als ik Joost goed volg, verwijst hij naar [deze regel](https://logius-standaarden.github.io/API-Design-Rules/#/core/semver), waar weer naar de officiele Semver tekst wordt verwezen. Een best-practice blok toevoegen zou kunnen maar mij lijkt deze vrij duidelijk voort te vloeien uit de SemVer specificatie.

Overigens staat er in BOMOS (neem aan dat dit verwikkeld is in het ADR beheermodel) het volgende: "*Minor Releases kunnen dus mogelijk technisch backwards incompatible zijn*." , wat in strijd is met SemVer.

2024-10-24 07:51 UTC, TheBonheurs commented on DesignRules.md
> +         Backward-compatible changes that do not affect any of the clients include the addition of new operations and schemas. Also, depending on the client's expectations, the addition of optional f
Heb deze iets aangepast

2025-02-11 08:33 UTC, TimvdLippe commented
Dit voorstel is afgewezen in het TO. Als er hernieuwde interesse is, dan kunnen we de wijziging heroverwegen.

2025-02-11 08:33 UTC, closed without merging