Added GEO section and rule
Logius-standaarden/API-Design-Rules pull request #137
Opened 2023-06-13 10:54 UTC by mrtn78

2023-06-13 12:03 UTC, strijm requested changes

2023-06-13 12:03 UTC, strijm commented on DesignRules.md
> +         <p>The NL API Strategy [[Geospatial Module]] provides rules for publishing geospatial data using Web APIs. Spatial data is data that describes anything with spatial extent (i.e. size, shape
Naast publiceren wordt er ook iets gezegd over het muteren van resources met geometrie.

2023-06-13 12:03 UTC, strijm commented on DesignRules.md
> +         <p>Geospatial data is more specific in that it is explicitly located relative to the Earth.</p>
Specifieker dan gewone data? 

"...explicitly located relative to the Earth," dat duidt op een locatie, maar dat staat ook al in de vorige zin/alinea.

2023-06-13 12:03 UTC, strijm commented on DesignRules.md
> +         <p>Aplying these rules on APIs for Geographic Information System (GIS) and Administrative functions is OPTIONAL.</p>
Deze zin kan w.m.b. weg, deze roept verwarring op. Hierboven staat dat de rules in de geo module toegepast moeten worden bij het specificeren van een API voor het afhandelen van geo informatie, en in deze zin staat dat het toepassen van de rules optioneel is bij het gebruik door GIS applicaties en administratieve toepassingen. Maar de geo module is juist bedoeld voor die toepassingen, althans m.n. administratieve toepassingen en voor het gebruik in GIS applicaties geldt dat API's voledig aan OGC API Features moeten voldoen.

2023-06-13 13:17 UTC, mrtn78 commented on DesignRules.md
> +         <p>The NL API Strategy [[Geospatial Module]] provides rules for publishing geospatial data using Web APIs. Spatial data is data that describes anything with spatial extent (i.e. size, shape
ik had deze zin deels overgenomen van https://docs.geostandaarden.nl/api/API-Strategie-mod-geo/#introduction vandaar alleen de focus op publiceren. zal ik het aanpassen of zo laten?

2023-06-28 14:28 UTC, strijm commented on DesignRules.md
> +         <p>The NL API Strategy [[Geospatial Module]] provides rules for publishing geospatial data using Web APIs. Spatial data is data that describes anything with spatial extent (i.e. size, shape
@mrtn78 Laat het dan maar zo staan. Ik zie nu dat er op regel 696 iets staat over het afhandelen van geo informatie, daar kan het muteren ook onder vallen.

2023-06-28 14:30 UTC, strijm approved these changes

2023-07-13 07:39 UTC, lvdbrink approved these changes
I found one typo (becomming > becoming) but other than that it looks good now!

2023-07-13 07:39 UTC, lvdbrink commented on Glossary.md
> +    <p><a href="https://www.ogc.org/">OGC</a> is a consortium of experts committed to improving access to geospatial, or location information.</p>
I would also add the full name here, i.e. Open Geospatial Consortium.

2023-07-13 07:39 UTC, lvdbrink commented on DesignRules.md
> +         <p>The NL API Strategy [[Geospatial Module]] provides rules for publishing geospatial data using Web APIs. Spatial data is data that describes anything with spatial extent (i.e. size, shape
Instead of 
> APIs containing [OGC](#dfn-ogc) compliant features should therefore be compliant with geospatial specific rules.

I would prefer something like 

> APIs containing geospatial content should therefore be compliant... 

And add a separate sentence, something like

> A separate module describes the rules for geospatial content and functions in APIs. It is based on international [OGC](#dfn-ogc) standards. 

Rationale: the GEO module handles both cases where OGC compliance is required, and cases where it isn't (in the latter case the GEO module still gives some rules for interoperability)

2023-07-13 07:39 UTC, lvdbrink commented on DesignRules.md
Again, the GEO module handles both cases where OGC compliance is required, and cases where it isn't; so I would delete this part:
>  to handle geospatial data in line with <a href="https://ogcapi.ogc.org/features/">the Open Geospatial Consortium (OGC) API Features.</a>

2023-07-13 07:39 UTC, lvdbrink commented on DesignRules.md
> +Geospatial content is becomming more common in every modern API. APIs containing [=OGC=] compliant features should therefore be compliant with geospatial specific rules.
typo 'becomming' > should be 'becoming'

2023-07-13 07:39 UTC, lvdbrink commented on DesignRules.md
When reading for a second time, I think this sentence can stay. It informs readers that the geo module is in line with OGC API features which is good info.

2023-07-20 08:19 UTC, merged